name: 09 Telegram IoT Bot
description: Check temperature and humidity and control an external LED remotely through a Telegram bot.
ports: []
bricks:
- arduino:telegram_bot:
    variables:
      TELEGRAM_BOT_TOKEN: ""
icon: 🤖
